project: lmms-eval
default_partition: kill-shared
modules:
  python: lang/Python/3.11.5-GCCcore-13.2.0
  cuda: system/CUDA/12.2.0
env_watch:
- scripts/setup_env.sh
- pyproject.toml
snapshot_excludes:
  - .github
  - docs